### PR TITLE
Added the ability to specify install location

### PR DESCRIPTION
**Pull request by the-djdj**
An install location can now be specified using `static-get -p <location> <package>`. The previous install system, `static-get -i <package>` effectively works out to `static-get -p / <package>`, but users can now change this if they so wish.

This pull request addresses @maximbaz's comment in #14:
> Nice feature! It would have been nice if we could configure a prefix, i.e. instead of installing to `/bin/` to be able to install to `/opt/bin/`

### CODE REVIEW

**Comment by max-baz** [comment]
Nice nice! 

I would recommend to follow a single responsibility principle and make `-p` _only_ set the prefix, not perform the installation. Then users would do `static-get -i <package>` or `static-get -i <package> -p <location>` depending on their needs.

**Comment by javier-lopez** [comment]
I agree with @maximbaz , `-p` should require `-i` explicitely, can someone make the modification before we merge?

**Comment by the-djdj** [comment]
I've made the modification and updated the test cases, but further input/testing would be welcome.

**Comment by max-baz** [comment]
Thanks!

Been testing a little, `static-get -p /tmp/opt -i htop` works great, but specifying the parameters in a different order doesn't work:

```
❯ ./static-get -i htop -p /tmp/opt              
Option '-p' requires a parameter -p   
```

**Comment by the-djdj** [comment]
I get the same issue using the other possible options (such as `-d`), perhaps it's an issue with how the arguments are handled?

**Comment by max-baz** [comment]
Ah, maybe, @javier-lopez will confirm :) But otherwise works well :)

**Comment by javier-lopez** [comment]
Great work, thank you both @the-djdj / @maximbaz 🍻 , I'm going ahead and merge this PR and I've created a new issue for tracking the parameter order issue, https://github.com/minos-org/minos-static/issues/16 , to anyone, feel free to take it, otherwise I'll work on it during the weekend.

Have a great day :shipit: =)!

**Pull request merged**
